name: Bug Report
description: File a bug report
type: "Bug"
assignees:
  - 42willow
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Is your issue related to plugins, themes, snippets, or something else?
      options:
        - Plugins
        - Themes
        - Snippets
        - Other
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: "What version of Schooltape are you running?"
      placeholder: "eg. v2.3.0"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome/Chromium-based
        - Microsoft Edge
    validations:
      required: true
