name: Component Todo

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  populate-todo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Populate todo
        run: |
          python assets/scripts/populate_todo.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: populate todo"
          git push"
