name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths-ignore:
      - "*.md"
      - "*.json"
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - "*.json"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oxc-project/oxlint-action@v3.0.0
